- name: Install nginx
  apt:
    name: "{{ web_package }}"
    state: present
    update_cache: yes

- name: Ensure nginx is running
  service:
    name: "{{ web_service }}"
    state: started
    enabled: yes

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart nginx
